<?php
/**
 * @var \Dev\ProductComments\Block\Switcher $block
*/

?>
<?php if (count($block->getStores())): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-target="dropdown">
                <?php foreach ($block->getStores() as $store): ?>
                    <li class="view-<?= $block->escapeHtml($store->getCode()) ?> switcher-option">
                        <a href="<?= $block->escapeHtml($store->getBaseUrl())?>">
                            <?= $block->escapeHtml($store->getName())?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>

