<?php
/**
 * @var $block Dev\ProductComments\Block\Widget\Products
 */
?>

<div class="products wrapper grid products-grid">
    <ol class="products list items product-items">
        <?php
        $products = $block->getProductCollection($block->getData('products_count'));
        ?>
        <?php foreach($products as $product) : ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-grid">
                    <a href="<?php echo $product->getUrlInStore() ?>" class="product photo product-item-photo" tabindex="-1">
                <span class="product-image-container" style="width:240px;">
                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                        <img class="product-image-photo"
                             src="<?php echo $block->getImage($product)?>"
                             width="135" height="135"
                             alt="<?php echo $product->getName() ?>"/>
                    </span>
                </span>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?php echo $product->getUrlInStore() ?>">
                                <?php echo $product->getName() ?>
                            </a>
                        </strong>
                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="3">
                    <span class="price-container price-final_price tax weee">
                        <span  data-price-amount="<?php echo $product->getPrice() ?>" data-price-type="finalPrice" class="price-wrapper ">
                            <span class="price">
                                <?php
                                $price = $product->getPrice();
                                echo $block->getPrice($price);
                                ?>
                            </span>
                        </span>
                    </span>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
